# Note: Smaller area and height values result in less lag.
# baseBlockSpeeds speed less than 0.4 may not work well.
# autoPlace will automatically move players to be fully in the elevator
# checkFloor will make sure all floors have glass blocks (at the cost of possible lag when starting a lift)
# preventEntry will prevent players from entering an active elevator (at the cost of possible lag when lifts are running)
metrics: true
maxLiftArea: 16
maxHeight: 256
debug: false
autoPlace: false
preventEntry: false
preventLeave: true
checkFloor: false
liftMobs: true
floorBlocks:
  - GLASS
  - "*_STAINED_GLASS"
buttonBlocks:
  - "*BUTTON"
signBlocks:
  - "*WALL_SIGN"
redstone: false
baseBlockSpeeds:
  IRON_BLOCK: 0.5
STRING_oneFloor: "There is only one floor."
STRING_currentFloor: "Current Floor"
STRING_dest: "ยง1Dest"
STRING_cantEnter: "Can't enter elevator in use"
STRING_cantLeave: "Can't leave elevator in use"
STRING_unsafe: "It is unsafe to leave a vehicle in a lift!"